name: Release

on:
  push:
    branches:
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Without this, there are no files in the directory.
    - uses: actions/checkout@v2

    # getting for branch name
    - uses: nelonoel/branch-name@v1.0.1

    - name: Set version name
      run: echo "VERSION_NAME=$(echo $BRANCH_NAME | cut -d '/' -f 2)" >> $GITHUB_ENV

    # using flutter
    - uses: subosito/flutter-action@v1
    - run: flutter channel stable
    - run: flutter upgrade
    - run: dart --version
    - run: flutter --version
    - run: flutter pub get

    # formatting
    - run: flutter format .

    # tagging version
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "$VERSION_NAME"
        git tag "$VERSION_NAME"
        git push origin "$VERSION_NAME"
